<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="OPENSANB-003342" name="tests.CadastrarUsuario" tests="2" failures="1" timestamp="2020-01-21T16:13:26 BRT" time="1.557" errors="0">
  <testcase name="testCadastrarUsuario2" time="0.520" classname="tests.CadastrarUsuario">
    <failure type="java.lang.AssertionError" message="expected [Cadastrado!
Nome: Nilton
Sobrenome: Lucio Correia
Sexo: Masculino
Comida:
Escolaridade: superior
Esportes: Futebol Corrida
Sugestoes:] but found [Cadastrado!
Nome: Nilton
Sobrenome: Lucio Correia
Sexo: Masculino
Comida: Carne Frango
Escolaridade: superior
Esportes: Futebol Corrida
Sugestoes:!]">
      <![CDATA[java.lang.AssertionError: expected [Cadastrado!
Nome: Nilton
Sobrenome: Lucio Correia
Sexo: Masculino
Comida:
Escolaridade: superior
Esportes: Futebol Corrida
Sugestoes:] but found [Cadastrado!
Nome: Nilton
Sobrenome: Lucio Correia
Sexo: Masculino
Comida: Carne Frango
Escolaridade: superior
Esportes: Futebol Corrida
Sugestoes:!]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at tests.CadastrarUsuario.testCadastrarUsuario2(CadastrarUsuario.java:70)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- testCadastrarUsuario2 -->
  <testcase name="testCadastrarUsuario" time="1.037" classname="tests.CadastrarUsuario"/>
</testsuite> <!-- tests.CadastrarUsuario -->
